
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbtgen'
version: '0.2.0'

require-dbt-version: [">=1.2.0", "<2.0.0"]
config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"
